screen:
    width: 1024
    height: 768
    splitter_size:
      left: 50
      right: 400
    assets:
      path: "/Users/felipenunes/projects/python-widgets/text-editor/assets" 
style: 
  pallete-path: "/Users/felipenunes/projects/python-widgets/text-editor/theme/palletes.json"
  theme: "dark"

